/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ssnfs.h"
#include <pwd.h>
#include <stdio.h>
#include <string.h>

int deletenl(char *str){
  size_t n;
  n = strlen(str);
  if(str[n-1] == '\n')
    str[n-1]=0;
  return 0;
}



void
ssnfsprog_1(char *host)
{
  CLIENT *clnt;
  create_output  *ocreate;
  create_input  icreate;
  list_output  *olist;
  list_input  ilist;
  delete_output  *odelete;
  delete_input  idelete;
  write_output  *owrite;
  write_input  iwrite;
  read_output  *oread;
  read_input  iread;
  copy_output  *ocopy;
  copy_input  icopy;

  /*Interface variables*/
  char user_name[10];
  char command[100];/*Read from command line*/
  char *token;/*variable for strtok*/
  char ch;
  const char *delim = " ";
  int i;

  clnt = clnt_create(host, SSNFSPROG, SSNFSVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror (host);
    exit (1);
  }
  else
    printf("Connected to server successfully!\n");
  printf("******************SSNFS environment******************\n");
  /*Get userid*/
  strcpy(user_name, getpwuid(getuid())->pw_name);
  printf("Your user id is: %s.\n", user_name);
  printf("Now you have access to the following operations:\n");
  printf("  CREATE A FILE:    create [file_name]\n");
  printf("  LIST ALL FILES:   list\n");
  printf("  DELETE A FILE:    delete [file_name]\n");
  printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
  printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
  printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
  printf("  EXIT:             exit\n");
  printf(">>");
  while(fgets(command,100,stdin)){
    deletenl(command);
    token = strtok(command," ");/*Get command*/

    /*Exit*/
    if(!strcmp(token,"exit")){
      printf("Exit SSNFS environment\n");
      break;
    }

    /*Create file for current user*/
    if(!strcmp(token,"create")){
      token = strtok(NULL, " ");/*file name*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      strcpy(icreate.user_name, user_name);
      strcpy(icreate.file_name, token);

      ocreate = create_file_1(&icreate, clnt);	 
      if (ocreate == (create_output *) NULL) {
	clnt_perror (clnt, "call failed");
      }
      else{
	printf("%s\n",ocreate->out_msg.out_msg_val);
      }
      printf(">>");
      continue;
    }

    /*List all files in user's directory*/
    if(!strcmp(token,"list")){
      strcpy(ilist.usrname,user_name);

      olist = list_files_1(&ilist, clnt);
      if (olist == (list_output *) NULL) {
	clnt_perror (clnt, "call failed");
      }
      else
	printf("%s\n",olist->out_msg.out_msg_val);
      printf(">>");
      continue;
    }

    /*Delete specified file*/
    if(!strcmp(token, "delete")){
      token = strtok(NULL, " ");/*file name*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      strcpy(idelete.user_name, user_name);
      strcpy(idelete.file_name, token);
      odelete = delete_file_1(&idelete, clnt);
      if (odelete == (delete_output *) NULL) {
	clnt_perror (clnt, "call failed");
      }
      else 
	printf("%s\n",odelete->out_msg.out_msg_val);
      printf(">>");
      continue;
    }

    if(!strcmp(token,"write")){
      strcpy(iwrite.user_name, user_name);
      token = strtok(NULL, " ");/*file name*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      strcpy(iwrite.file_name, token);
      token = strtok(NULL, " ");/*offset*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      iwrite.offset = atoi(token);
      token = strtok(NULL, " ");/*numbytes*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      iwrite.numbytes = atoi(token);
	      
      iwrite.buffer.buffer_val = malloc(iwrite.numbytes * sizeof(char));
      iwrite.buffer.buffer_len = 0;

      printf("Type in the contents:\n");
      i=0;
      while(i<iwrite.numbytes){
	if((iwrite.buffer.buffer_val[i]=getchar())==EOF)break;
	i++;
      }
      iwrite.buffer.buffer_len = i;
      /*printf("test\n");
	for(i=0;i<iwrite.buffer.buffer_len;i++)
	printf("%c",iwrite.buffer.buffer_val[i]);*/

      while ((ch = fgetc(stdin)) != EOF && ch != '\n');/*Clear stdin buffer*/
	    
      owrite = write_file_1(&iwrite, clnt);
      if (owrite == (write_output *) NULL) {
	clnt_perror (clnt, "call failed");
      }
      else
	printf("%s\n",owrite->out_msg.out_msg_val);
      printf(">>");
      continue;	      
    }
	  

    /*Read file*/
    if(!strcmp(token,"read")){
      strcpy(iread.user_name, user_name);
      token = strtok(NULL, " ");/*file name*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      strcpy(iread.file_name, token);
      token = strtok(NULL, " ");/*offset*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT: exit\n");
	printf(">>");
	continue;
      }
      iread.offset = atoi(token);
      token = strtok(NULL, " ");/*numbytes*/
      if(token==NULL){
	printf("ERROR!FILENAME SHOULD BE SPECIFIED!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      iread.numbytes = atoi(token);

      oread = read_file_1(&iread, clnt);
      if (oread == (read_output *) NULL) {
	clnt_perror (clnt, "call failed");
      }
      else{
	oread->out_msg.out_msg_val[oread->out_msg.out_msg_len] = '\0';
	printf("%s\n",oread->out_msg.out_msg_val);
      }
      printf(">>");
      continue;	      
    }
	  
    /*Copy from_file to to-file*/
    if(!strcmp(token,"copy")){
      strcpy(icopy.user_name, user_name);
      token = strtok(NULL, " ");/*from_filename*/
      if(token == NULL){
	printf("Invalid Input!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      strcpy(icopy.from_filename, token);
	    
      token = strtok(NULL, " ");/*to_filename*/
      if(token == NULL){
	printf("Invalid Input!\n");
	printf("usage:\n");
	printf("  CREATE FILE: create [file_name]\n");
	printf("  LIST ALL FILES:   list\n");
	printf("  DELETE A FILE:    delete [file_name]\n");
	printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
	printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
	printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
	printf("  EXIT:             exit\n");
	printf(">>");
	continue;
      }
      strcpy(icopy.to_filename, token);

      if(!strcmp(icopy.to_filename,icopy.from_filename)){
	printf("files are the same, please input two different files,%s,%s\n",icopy.user_name,icopy.from_filename);
	printf(">>");
	continue;
      }

      ocopy = copy_file_1(&icopy, clnt);
      if (ocopy == (copy_output *) NULL) {
	clnt_perror (clnt, "call failed");
      }
      else
	printf("%s\n",ocopy->out_msg.out_msg_val);
      printf(">>");
      continue;	    
    }  

    printf("Invalid Input!\n");
    printf("usage:\n");
    printf("  CREATE FILE: create [file_name]\n");
    printf("  LIST ALL FILES:   list\n");
    printf("  DELETE A FILE:    delete [file_name]\n");
    printf("  WRITE TO A FILE:  write [file_name] [offset] [numbytes]\n");
    printf("  READ A FILE:      read [file_name] [offset] [numbytes]\n");
    printf("  COPY A FILE:      copy [from_filename] [to_filename]\n");
    printf("  EXIT:             exit\n");
    printf(">>");
  }




#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ssnfsprog_1 (host);
exit (0);
}
