/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ssnfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

create_output *
create_file_1(create_input *argp, CLIENT *clnt)
{
	static create_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, create_file,
		(xdrproc_t) xdr_create_input, (caddr_t) argp,
		(xdrproc_t) xdr_create_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

list_output *
list_files_1(list_input *argp, CLIENT *clnt)
{
	static list_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, list_files,
		(xdrproc_t) xdr_list_input, (caddr_t) argp,
		(xdrproc_t) xdr_list_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

delete_output *
delete_file_1(delete_input *argp, CLIENT *clnt)
{
	static delete_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, delete_file,
		(xdrproc_t) xdr_delete_input, (caddr_t) argp,
		(xdrproc_t) xdr_delete_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

write_output *
write_file_1(write_input *argp, CLIENT *clnt)
{
	static write_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, write_file,
		(xdrproc_t) xdr_write_input, (caddr_t) argp,
		(xdrproc_t) xdr_write_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

read_output *
read_file_1(read_input *argp, CLIENT *clnt)
{
	static read_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, read_file,
		(xdrproc_t) xdr_read_input, (caddr_t) argp,
		(xdrproc_t) xdr_read_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

copy_output *
copy_file_1(copy_input *argp, CLIENT *clnt)
{
	static copy_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, copy_file,
		(xdrproc_t) xdr_copy_input, (caddr_t) argp,
		(xdrproc_t) xdr_copy_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
